version: '3.8'

services:
  zenkink-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
      - ../data:/app/data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    env_file:
      - ../.env
    depends_on:
      - redis
    networks:
      - zenkink-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zenkink-network

volumes:
  redis_data:

networks:
  zenkink-network:
    driver: bridge